main: me.Ice.antiblockglitch.Anticheat
name: AntiBlockGlitch
version: 1.0.2
author: Ice
api-version: 1.16
depends: [WorldEdit, WorldGuard]

permissions:
   antiblockglitch.override:
      description: Allows player to bypass the anti block glitch
commands:
  antiblockreload:
    description: Reloads the plugin config
    permission: antiblockglitch.reload
